package me.eldodebug.flax.management.mods;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class ModCatalog {

    private static final List<ModDefinition> DEFINITIONS = buildDefinitions();

    private ModCatalog() {
    }

    public static List<ModDefinition> definitions() {
        return DEFINITIONS;
    }

    private static List<ModDefinition> buildDefinitions() {
        List<ModDefinition> mods = new ArrayList<>();
        mods.add(new ModDefinition("animations", "Animations", "Animations module", ModCategory.RENDER));
        mods.add(new ModDefinition("aim_assist", "Aim Assist", "Aim Assist module", ModCategory.GHOST));
        mods.add(new ModDefinition("apple_skin", "AppleSkin", "AppleSkin module", ModCategory.HUD));
        mods.add(new ModDefinition("armor_status", "Armor Status", "Armor Status module", ModCategory.HUD));
        mods.add(new ModDefinition("arraylist", "ArrayList", "ArrayList module", ModCategory.HUD));
        mods.add(new ModDefinition("async_screenshot", "Async Screenshot", "Async Screenshot module", ModCategory.OTHER));
        mods.add(new ModDefinition("auto_text", "Auto Text", "Auto Text module", ModCategory.OTHER));
        mods.add(new ModDefinition("block_info", "Block Info", "Block Info module", ModCategory.HUD));
        mods.add(new ModDefinition("block_overlay", "Block Overlay", "Block Overlay module", ModCategory.RENDER));
        mods.add(new ModDefinition("blood_particles", "Blood Particles", "Blood Particles module", ModCategory.RENDER));
        mods.add(new ModDefinition("borderless_fullscreen", "Borderless Fullscreen", "Borderless Fullscreen module", ModCategory.OTHER));
        mods.add(new ModDefinition("boss_health", "Boss Health", "Boss Health module", ModCategory.HUD));
        mods.add(new ModDefinition("bow_zoom", "Bow Zoom", "Bow Zoom module", ModCategory.PLAYER));
        mods.add(new ModDefinition("breadcrumbs", "Breadcrumbs", "Breadcrumbs module", ModCategory.RENDER));
        mods.add(new ModDefinition("calendar", "Calendar", "Calendar module", ModCategory.HUD));
        mods.add(new ModDefinition("chat", "Chat", "Chat module", ModCategory.OTHER));
        mods.add(new ModDefinition("chat_translate", "Chat Translate", "Chat Translate module", ModCategory.OTHER));
        mods.add(new ModDefinition("chunk_animator", "Chunk Animator", "Chunk Animator module", ModCategory.RENDER));
        mods.add(new ModDefinition("chunk_borders", "Chunk Borders", "Chunk Borders module", ModCategory.WORLD));
        mods.add(new ModDefinition("clear_glass", "Clear Glass", "Clear Glass module", ModCategory.RENDER));
        mods.add(new ModDefinition("clear_water", "Clear Water", "Clear Water module", ModCategory.RENDER));
        mods.add(new ModDefinition("client_spoofer", "Client Spoofer", "Client Spoofer module", ModCategory.OTHER));
        mods.add(new ModDefinition("clock", "Clock", "Clock module", ModCategory.HUD));
        mods.add(new ModDefinition("color_saturation", "Color Saturation", "Color Saturation module", ModCategory.RENDER));
        mods.add(new ModDefinition("combo_counter", "Combo Counter", "Combo Counter module", ModCategory.HUD));
        mods.add(new ModDefinition("compass", "Compass", "Compass module", ModCategory.HUD));
        mods.add(new ModDefinition("coords", "Coords", "Coords module", ModCategory.HUD));
        mods.add(new ModDefinition("cps_display", "CPS Display", "CPS Display module", ModCategory.HUD));
        mods.add(new ModDefinition("crosshair", "Crosshair", "Crosshair module", ModCategory.RENDER));
        mods.add(new ModDefinition("custom_held_items", "Custom Held Items", "Custom Held Items module", ModCategory.RENDER));
        mods.add(new ModDefinition("damage_particles", "Damage Particles", "Damage Particles module", ModCategory.RENDER));
        mods.add(new ModDefinition("damage_tilt", "Damage Tilt", "Damage Tilt module", ModCategory.RENDER));
        mods.add(new ModDefinition("damage_tint", "Damage Tint", "Damage Tint module", ModCategory.RENDER));
        mods.add(new ModDefinition("day_counter", "Day Counter", "Day Counter module", ModCategory.HUD));
        mods.add(new ModDefinition("auto_clicker", "Auto Clicker", "Auto Clicker module", ModCategory.GHOST));
        mods.add(new ModDefinition("discord_rpc", "Discord RPC", "Discord RPC module", ModCategory.OTHER));
        mods.add(new ModDefinition("ears", "Ears", "Ears module", ModCategory.RENDER));
        mods.add(new ModDefinition("esp", "ESP", "ESP module", ModCategory.RENDER));
        mods.add(new ModDefinition("entity_culling", "Entity Culling", "Entity Culling module", ModCategory.RENDER));
        mods.add(new ModDefinition("far_camera", "Far Camera", "Far Camera module", ModCategory.RENDER));
        mods.add(new ModDefinition("female_gender", "Female Gender", "Female Gender module", ModCategory.RENDER));
        mods.add(new ModDefinition("fast_place", "Fast Place", "Fast Place module", ModCategory.PLAYER));
        mods.add(new ModDefinition("fov_modifier", "FOV Modifier", "FOV Modifier module", ModCategory.PLAYER));
        mods.add(new ModDefinition("fps_boost", "FPS Boost", "FPS Boost module", ModCategory.OTHER));
        mods.add(new ModDefinition("fps_display", "FPS Display", "FPS Display module", ModCategory.HUD));
        mods.add(new ModDefinition("fps_limiter", "FPS Limiter", "FPS Limiter module", ModCategory.OTHER));
        mods.add(new ModDefinition("fps_spoofer", "FPS Spoofer", "FPS Spoofer module", ModCategory.OTHER));
        mods.add(new ModDefinition("freelook", "Freelook", "Freelook module", ModCategory.PLAYER));
        mods.add(new ModDefinition("fullbright", "Fullbright", "Fullbright module", ModCategory.PLAYER));
        mods.add(new ModDefinition("glint_color", "Glint Color", "Glint Color module", ModCategory.RENDER));
        mods.add(new ModDefinition("internal_settings", "Internal Settings", "Internal Settings module", ModCategory.OTHER));
        mods.add(new ModDefinition("godbridge_assist", "Godbridge Assist", "Godbridge Assist module", ModCategory.GHOST));
        mods.add(new ModDefinition("ghost_nametags", "Ghost Nametags", "Ghost Nametags module", ModCategory.GHOST));
        mods.add(new ModDefinition("healthbar", "Healthbar", "Healthbar module", ModCategory.HUD));
        mods.add(new ModDefinition("health_display", "Health Display", "Health Display module", ModCategory.HUD));
        mods.add(new ModDefinition("hitbox", "Hitbox", "Hitbox module", ModCategory.RENDER));
        mods.add(new ModDefinition("hit_color", "Hit Color", "Hit Color module", ModCategory.RENDER));
        mods.add(new ModDefinition("hit_delay_fix", "Hit Delay Fix", "Hit Delay Fix module", ModCategory.PLAYER));
        mods.add(new ModDefinition("horse_stats", "Horse Stats", "Horse Stats module", ModCategory.HUD));
        mods.add(new ModDefinition("hypixel", "Hypixel", "Hypixel module", ModCategory.OTHER));
        mods.add(new ModDefinition("hypixel_quickplay", "Hypixel QuickPlay", "Hypixel QuickPlay module", ModCategory.OTHER));
        mods.add(new ModDefinition("image_display", "Image Display", "Image Display module", ModCategory.HUD));
        mods.add(new ModDefinition("inventory_display", "Inventory Display", "Inventory Display module", ModCategory.HUD));
        mods.add(new ModDefinition("inventory", "Inventory", "Inventory module", ModCategory.OTHER));
        mods.add(new ModDefinition("item_info", "Item Info", "Item Info module", ModCategory.HUD));
        mods.add(new ModDefinition("item_physics", "Item Physics", "Item Physics module", ModCategory.RENDER));
        mods.add(new ModDefinition("items_2d", "Items 2D", "Items 2D module", ModCategory.RENDER));
        mods.add(new ModDefinition("jump_circle", "Jump Circle", "Jump Circle module", ModCategory.RENDER));
        mods.add(new ModDefinition("jump_reset", "Jump Reset", "Jump Reset module", ModCategory.PLAYER));
        mods.add(new ModDefinition("keystrokes", "Keystrokes", "Keystrokes module", ModCategory.HUD));
        mods.add(new ModDefinition("kill_effects", "Kill Effects", "Kill Effects module", ModCategory.RENDER));
        mods.add(new ModDefinition("kill_sounds", "Kill Sounds", "Kill Sounds module", ModCategory.OTHER));
        mods.add(new ModDefinition("mechvibes", "Mechvibes", "Mechvibes module", ModCategory.OTHER));
        mods.add(new ModDefinition("memory_usage", "Memory Usage", "Memory Usage module", ModCategory.HUD));
        mods.add(new ModDefinition("minemen", "Minemen", "Minemen module", ModCategory.OTHER));
        mods.add(new ModDefinition("minimal_damage_shake", "Minimal Damage Shake", "Minimal Damage Shake module", ModCategory.RENDER));
        mods.add(new ModDefinition("minimal_view_bobbing", "Minimal View Bobbing", "Minimal View Bobbing module", ModCategory.RENDER));
        mods.add(new ModDefinition("minimap", "Minimap", "Minimap module", ModCategory.HUD));
        mods.add(new ModDefinition("mobends", "MoBends", "MoBends module", ModCategory.RENDER));
        mods.add(new ModDefinition("modern_hotbar", "Modern Hotbar", "Modern Hotbar module", ModCategory.HUD));
        mods.add(new ModDefinition("motion_blur", "Motion Blur", "Motion Blur module", ModCategory.RENDER));
        mods.add(new ModDefinition("mouse_strokes", "Mouse Strokes", "Mouse Strokes module", ModCategory.HUD));
        mods.add(new ModDefinition("name_display", "Name Display", "Name Display module", ModCategory.HUD));
        mods.add(new ModDefinition("name_protect", "Name Protect", "Name Protect module", ModCategory.OTHER));
        mods.add(new ModDefinition("nametag", "Nametag", "Nametag module", ModCategory.RENDER));
        mods.add(new ModDefinition("overlay_editor", "Overlay Editor", "Overlay Editor module", ModCategory.OTHER));
        mods.add(new ModDefinition("pack_display", "Pack Display", "Pack Display module", ModCategory.HUD));
        mods.add(new ModDefinition("particle_customizer", "Particle Customizer", "Particle Customizer module", ModCategory.RENDER));
        mods.add(new ModDefinition("ping_display", "Ping Display", "Ping Display module", ModCategory.HUD));
        mods.add(new ModDefinition("player_counter", "Player Counter", "Player Counter module", ModCategory.HUD));
        mods.add(new ModDefinition("player_display", "Player Display", "Player Display module", ModCategory.HUD));
        mods.add(new ModDefinition("player_list", "Player List", "Player List module", ModCategory.HUD));
        mods.add(new ModDefinition("player_predicator", "Player Predicator", "Player Predicator module", ModCategory.GHOST));
        mods.add(new ModDefinition("playtime_display", "Playtime Display", "Playtime Display module", ModCategory.HUD));
        mods.add(new ModDefinition("potion_counter", "Potion Counter", "Potion Counter module", ModCategory.HUD));
        mods.add(new ModDefinition("potion_status", "Potion Status", "Potion Status module", ModCategory.HUD));
        mods.add(new ModDefinition("projectile_trail", "Projectile Trail", "Projectile Trail module", ModCategory.RENDER));
        mods.add(new ModDefinition("quick_switch", "Quick Switch", "Quick Switch module", ModCategory.PLAYER));
        mods.add(new ModDefinition("raw_input", "Raw Input", "Raw Input module", ModCategory.OTHER));
        mods.add(new ModDefinition("reach_circles", "Reach Circles", "Reach Circles module", ModCategory.RENDER));
        mods.add(new ModDefinition("reach_display", "Reach Display", "Reach Display module", ModCategory.HUD));
        mods.add(new ModDefinition("rearview", "Rearview", "Rearview module", ModCategory.RENDER));
        mods.add(new ModDefinition("scoreboard", "Scoreboard", "Scoreboard module", ModCategory.HUD));
        mods.add(new ModDefinition("safe_walk", "Safe Walk", "Safe Walk module", ModCategory.PLAYER));
        mods.add(new ModDefinition("server_ip_display", "Server IP Display", "Server IP Display module", ModCategory.HUD));
        mods.add(new ModDefinition("session_info", "Session Info", "Session Info module", ModCategory.HUD));
        mods.add(new ModDefinition("shiny_pots", "Shiny Pots", "Shiny Pots module", ModCategory.RENDER));
        mods.add(new ModDefinition("skin3d", "Skin3D", "Skin3D module", ModCategory.RENDER));
        mods.add(new ModDefinition("skin_protect", "Skin Protect", "Skin Protect module", ModCategory.OTHER));
        mods.add(new ModDefinition("slow_swing", "Slow Swing", "Slow Swing module", ModCategory.RENDER));
        mods.add(new ModDefinition("sound_modifier", "Sound Modifier", "Sound Modifier module", ModCategory.OTHER));
        mods.add(new ModDefinition("sound_subtitles", "Sound Subtitles", "Sound Subtitles module", ModCategory.OTHER));
        mods.add(new ModDefinition("speedometer", "Speedometer", "Speedometer module", ModCategory.HUD));
        mods.add(new ModDefinition("stopwatch", "Stopwatch", "Stopwatch module", ModCategory.HUD));
        mods.add(new ModDefinition("tab_editor", "Tab Editor", "Tab Editor module", ModCategory.OTHER));
        mods.add(new ModDefinition("taplook", "Taplook", "Taplook module", ModCategory.PLAYER));
        mods.add(new ModDefinition("target_indicator", "Target Indicator", "Target Indicator module", ModCategory.RENDER));
        mods.add(new ModDefinition("target_info", "Target Info", "Target Info module", ModCategory.HUD));
        mods.add(new ModDefinition("time_changer", "Time Changer", "Time Changer module", ModCategory.WORLD));
        mods.add(new ModDefinition("tnt_timer", "TNT Timer", "TNT Timer module", ModCategory.HUD));
        mods.add(new ModDefinition("toggle_sneak", "Toggle Sneak", "Toggle Sneak module", ModCategory.PLAYER));
        mods.add(new ModDefinition("toggle_sprint", "Toggle Sprint", "Toggle Sprint module", ModCategory.PLAYER));
        mods.add(new ModDefinition("uhc_overlay", "UHC Overlay", "UHC Overlay module", ModCategory.HUD));
        mods.add(new ModDefinition("wavey_capes", "Wavey Capes", "Wavey Capes module", ModCategory.RENDER));
        mods.add(new ModDefinition("waypoint", "Waypoint", "Waypoint module", ModCategory.WORLD));
        mods.add(new ModDefinition("weather_changer", "Weather Changer", "Weather Changer module", ModCategory.WORLD));
        mods.add(new ModDefinition("weather_display", "Weather Display", "Weather Display module", ModCategory.HUD));
        mods.add(new ModDefinition("zoom", "Zoom", "Zoom module", ModCategory.PLAYER));
        return Collections.unmodifiableList(mods);
    }
}
